/**
 * DOMAIN LAYER - AI Data Contract
 * File: server/domain/models/AITypes.ts
 *
 * Defines the contract between the Domain layer and the abstract AI Parser.
 * Notice: AI generates drafts with existing team member IDs (never database IDs).
 * Domain layer subsequently validates this contract and generates database IDs.
 */

import { UserRole } from './User.ts';

/**
 * Team Directory payload provided to the AI Parser.
 * Strictly excludes passwords, hashes, and session tokens.
 */
export interface TeamMemberDirectoryItem {
  id: string;
  name: string;
  role: UserRole;
  specialization: string;
  skills: string[];
}

/**
 * Raw task draft generated by the AI Parser.
 */
export interface AITaskDraft {
  title: string;
  description: string;
  assigneeId: string;
  deadline: string; // ISO date format YYYY-MM-DD
  estimatedHours: number;
}

/**
 * Raw project draft generated by the AI Parser.
 */
export interface AIProjectDraft {
  name: string;
  clientName: string;
  description: string;
  managerId: string;
  deadline: string; // ISO date format YYYY-MM-DD
  tasks: AITaskDraft[];
}

/**
 * Complete structured payload returned by the AI Parser.
 */
export interface AITranscriptOutput {
  projects: AIProjectDraft[];
}
